package com.github.suzuki0keiichi.nomorescript.bridge

class JsFunction0[A, B](val function: (A) => B)
class JsFunction1[A, B, C](val function: (A, B) => C)
class JsFunction2[A, B, C, D](val function: (A, B, C) => D)
class JsFunction3[A, B, C, D, E](val function: (A, B, C, D) => E)
class JsFunction4[A, B, C, D, E, F](val function: (A, B, C, D, E) => F)
class JsFunction5[A, B, C, D, E, F, G](val function: (A, B, C, D, E, F) => G)
class JsFunction6[A, B, C, D, E, F, G, H](val function: (A, B, C, D, E, F, G) => H)
class JsFunction7[A, B, C, D, E, F, G, H, I](val function: (A, B, C, D, E, F, G, H) => I)
class JsFunction8[A, B, C, D, E, F, G, H, I, J](val function: (A, B, C, D, E, F, G, H, I) => J)
class JsFunction9[A, B, C, D, E, F, G, H, I, J, K](val function: (A, B, C, D, E, F, G, H, I, J) => K)
class JsFunction10[A, B, C, D, E, F, G, H, I, J, K, L](val function: (A, B, C, D, E, F, G, H, I, J, K) => L)
class JsFunction11[A, B, C, D, E, F, G, H, I, J, K, L, M](val function: (A, B, C, D, E, F, G, H, I, J, K, L) => M)
class JsFunction12[A, B, C, D, E, F, G, H, I, J, K, L, M, N](val function: (A, B, C, D, E, F, G, H, I, J, K, L, M) => N)
class JsFunction13[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O](val function: (A, B, C, D, E, F, G, H, I, J, K, L, M, N) => O)
class JsFunction14[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P](val function: (A, B, C, D, E, F, G, H, I, J, K, L, M, N, O) => P)
class JsFunction15[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q](val function: (A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P) => Q)
class JsFunction16[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R](val function: (A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q) => R)
class JsFunction17[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S](val function: (A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R) => S)
class JsFunction18[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T](val function: (A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S) => T)
class JsFunction19[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U](val function: (A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T) => U)
class JsFunction20[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V](val function: (A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U) => V)
class JsFunction21[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W](val function: (A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V) => W)

object bridge {
  implicit def toJsFunction0[A, B](function: (A) => B) = new JsFunction0(function)
  implicit def toJsFunction1[A, B, C](function: (A, B) => C) = new JsFunction1(function)
  implicit def toJsFunction2[A, B, C, D](function: (A, B, C) => D) = new JsFunction2(function)
  implicit def toJsFunction3[A, B, C, D, E](function: (A, B, C, D) => E) = new JsFunction3(function)
  implicit def toJsFunction4[A, B, C, D, E, F](function: (A, B, C, D, E) => F) = new JsFunction4(function)
  implicit def toJsFunction5[A, B, C, D, E, F, G](function: (A, B, C, D, E, F) => G) = new JsFunction5(function)
  implicit def toJsFunction6[A, B, C, D, E, F, G, H](function: (A, B, C, D, E, F, G) => H) = new JsFunction6(function)
  implicit def toJsFunction7[A, B, C, D, E, F, G, H, I](function: (A, B, C, D, E, F, G, H) => I) = new JsFunction7(function)
  implicit def toJsFunction8[A, B, C, D, E, F, G, H, I, J](function: (A, B, C, D, E, F, G, H, I) => J) = new JsFunction8(function)
  implicit def toJsFunction9[A, B, C, D, E, F, G, H, I, J, K](function: (A, B, C, D, E, F, G, H, I, J) => K) = new JsFunction9(function)
  implicit def toJsFunction10[A, B, C, D, E, F, G, H, I, J, K, L](function: (A, B, C, D, E, F, G, H, I, J, K) => L) = new JsFunction10(function)
  implicit def toJsFunction11[A, B, C, D, E, F, G, H, I, J, K, L, M](function: (A, B, C, D, E, F, G, H, I, J, K, L) => M) = new JsFunction11(function)
  implicit def toJsFunction12[A, B, C, D, E, F, G, H, I, J, K, L, M, N](function: (A, B, C, D, E, F, G, H, I, J, K, L, M) => N) = new JsFunction12(function)
  implicit def toJsFunction13[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O](function: (A, B, C, D, E, F, G, H, I, J, K, L, M, N) => O) = new JsFunction13(function)
  implicit def toJsFunction14[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P](function: (A, B, C, D, E, F, G, H, I, J, K, L, M, N, O) => P) = new JsFunction14(function)
  implicit def toJsFunction15[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q](function: (A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P) => Q) = new JsFunction15(function)
  implicit def toJsFunction16[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R](function: (A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q) => R) = new JsFunction16(function)
  implicit def toJsFunction17[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S](function: (A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R) => S) = new JsFunction17(function)
  implicit def toJsFunction18[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T](function: (A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S) => T) = new JsFunction18(function)
  implicit def toJsFunction19[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U](function: (A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T) => U) = new JsFunction19(function)
  implicit def toJsFunction20[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V](function: (A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U) => V) = new JsFunction20(function)
  implicit def toJsFunction21[A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W](function: (A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V) => W) = new JsFunction21(function)
}
